In [11]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt

import matplotlib as mpl

mpl.rcParams['axes.spines.left'] = False
mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.spines.top'] = False
mpl.rcParams['axes.spines.bottom'] = False
mpl.rcParams.update({"axes.grid" : True, "axes.grid.which": "major"})

In [12]:
url_p1_train ='https://raw.githubusercontent.com/3eltran23/CS5056/master/data/SVM/P1/ExNLS_train.csv'
url_p1_test = 'https://raw.githubusercontent.com/3eltran23/CS5056/master/data/SVM/P1/ExNLS_test.csv'

dataset = pd.read_csv(url_p1_train)
dataTest =pd.read_csv(url_p1_test)



dataTest

    ID    X1    X2  y
0    1  2.51  2.36  1
1    2  0.39 -0.10 -1
2    3 -0.62  0.39 -1
3    4 -1.21  0.95  1
4    5  2.12 -0.38  1
5    6 -0.04 -0.41 -1
6    7 -0.02 -0.39 -1
7    8  0.94 -0.06 -1
8    9  1.82  2.10  1
9   10  1.59  1.76  1
10  11  1.92  0.84  1
11  12  1.78  0.75  1
12  13  0.07  0.70 -1
13  14 -1.99  0.56 -1
14  15  0.62 -0.69 -1
15  16 -0.06 -0.71 -1
16  17  0.84  1.36  1
17  18 -1.47  0.77 -1
18  19 -0.48 -0.11 -1
19  20  1.42  1.88  1